### ISSUE TITLE
 modifiedRecursive in rew level

### ISSUE THREAD

**Issue by dalitmilshtein** [JimGrange/trimr#7]
I switched to a new computer. I installed R packages again. Also TRIMR. When I tried to run a script I had run successfully many times:
DFtrim <- modifiedRecursive (data = Data, minRT = 150, digits = 0,  returnType = "raw") # raw levels
  I received the following error message: Error in modifiedRecursive (data = Data, minRT = 150, digits = 0,    unused argument (returnType = "raw")

**Comment by JimGrange** [comment]
I can't seem to replicate this issue. Are you still experiencing the problem?
