### ISSUE TITLE
now raw output when using both perCondition=TRUE and perParticipant=TRUE

### ISSUE THREAD

**Issue by yanina-prystauka** [JimGrange/trimr#8]
This produces an empty structure:
`trimmedData <- sdTrim(data = forTrimming, minRT = 300, sd = 2, perCondition = TRUE, perParticipant = TRUE,omitErrors = FALSE, returnType = 'raw', digits=0)`

However, if I change returnType to "mean", then everything works.

**Comment by JimGrange** [comment]
Please try the developmental version. Overview of changes here:

https://www.jimgrange.org/post/update-to-trimr-a-response-time-trimming-package-in-r/

Let me know if the problem persists.
